const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO';
const RESET_CART = 'RESET_CART'

module.exports = {
    ADD_TO_CART,
    REMOVE_CART_ITEM,
    SAVE_SHIPPING_INFO,
    RESET_CART
}