const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
const CREATE_ORDER_FALSE = 'CREATE_ORDER_FALSE';

const MY_ORDER_REQUEST = 'MY_ORDER_REQUEST';
const MY_ORDER_SUCCESS = 'MY_ORDER_SUCCESS';
const MY_ORDER_FALSE = 'MY_ORDER_FALSE';

const DETAIL_ORDER_REQUEST = 'DETAIL_ORDER_REQUEST';
const DETAIL_ORDER_SUCCESS = 'DETAIL_ORDER_SUCCESS';
const DETAIL_ORDER_FALSE = 'DETAIL_ORDER_FALSE';

const CLEAR_ERROR = 'CLEAR_ERRO';

module.exports = {
    CREATE_ORDER_REQUEST,
    CREATE_ORDER_SUCCESS,
    CREATE_ORDER_FALSE,
    MY_ORDER_REQUEST,
    MY_ORDER_SUCCESS,
    MY_ORDER_FALSE,
    DETAIL_ORDER_REQUEST,
    DETAIL_ORDER_SUCCESS,
    DETAIL_ORDER_FALSE,
    CLEAR_ERROR
}