const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
const CREATE_ORDER_FALSE = 'CREATE_ORDER_FALSE';

const MY_ORDER_REQUEST = 'MY_ORDER_REQUEST';
const MY_ORDER_SUCCESS = 'MY_ORDER_SUCCESS';
const MY_ORDER_FALSE = 'MY_ORDER_FALSE';

const DETAIL_ORDER_REQUEST = 'DETAIL_ORDER_REQUEST';
const DETAIL_ORDER_SUCCESS = 'DETAIL_ORDER_SUCCESS';
const DETAIL_ORDER_FALSE = 'DETAIL_ORDER_FALSE';

const ALL_ORDER_REQUEST = 'ALL_ORDER_REQUEST';
const ALL_ORDER_SUCCESS = 'ALL_ORDER_SUCCESS';
const ALL_ORDER_FALSE = 'ALL_ORDER_FALSE';

const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
const DELETE_ORDER_FALSE = 'DELETE_ORDER_FALSE';
const DELETE_ORDER_RESET = 'DELETE_ORDER_RESET';

const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
const UPDATE_ORDER_FALSE = 'UPDATE_ORDER_FALSE';
const UPDATE_ORDER_RESET = 'UPDATE_ORDER_RESET';

const CLEAR_ERROR = 'CLEAR_ERRO';


module.exports = {
    CREATE_ORDER_REQUEST,
    CREATE_ORDER_SUCCESS,
    CREATE_ORDER_FALSE,
    MY_ORDER_REQUEST,
    MY_ORDER_SUCCESS,
    MY_ORDER_FALSE,
    DETAIL_ORDER_REQUEST,
    DETAIL_ORDER_SUCCESS,
    DETAIL_ORDER_FALSE,
    ALL_ORDER_REQUEST,
    ALL_ORDER_SUCCESS,
    ALL_ORDER_FALSE,
    DELETE_ORDER_REQUEST,
    DELETE_ORDER_SUCCESS,
    DELETE_ORDER_FALSE,
    DELETE_ORDER_RESET,
    UPDATE_ORDER_REQUEST,
    UPDATE_ORDER_SUCCESS,
    UPDATE_ORDER_FALSE,
    UPDATE_ORDER_RESET,
    CLEAR_ERROR
}