const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
const CREATE_ORDER_FALSE = 'CREATE_ORDER_FALSE';

const CLEAR_ERROR = 'CLEAR_ERRO';

module.exports = {
    CREATE_ORDER_REQUEST,
    CREATE_ORDER_SUCCESS,
    CREATE_ORDER_FALSE,
    CLEAR_ERROR
}