const PRODUCTS_LIST_REQUEST = "PRODUCTS_LIST_REQUEST";
const PRODUCTS_LIST_SUCCESS = "PRODUCTS_LIST_SUCCESS";
const PRODUCTS_LIST_FALSE = "PRODUCTS_LIST_FALSE";

const PRODUCTS_DETAIL_REQUEST = "PRODUCTS_DETAIL_REQUEST";
const PRODUCTS_DETAIL_SUCCESS = "PRODUCTS_DETAIL_SUCCESS";
const PRODUCTS_DETAIL_FALSE = "PRODUCTS_DETAIL_FALSE";

const PRODUCTS_REVIEW_REQUEST = "PRODUCTS_REVIEW_REQUEST";
const PRODUCTS_REVIEW_SUCCESS = "PRODUCTS_REVIEW_SUCCESS";
const PRODUCTS_REVIEW_RESET = "PRODUCTS_REVIEW_RESET";
const PRODUCTS_REVIEW_FALSE = "PRODUCTS_REVIEW_FALSE";

const PRODUCTS_REVIEW_GET_REQUEST = "PRODUCTS_REVIEW_GET_REQUEST";
const PRODUCTS_REVIEW_GET_SUCCESS = "PRODUCTS_REVIEW_GET_SUCCESS";
const PRODUCTS_REVIEW_GET_FALSE = "PRODUCTS_REVIEW_GET_FALSE";

const PRODUCTS_REVIEW_DELETE_REQUEST = "PRODUCTS_REVIEW_DELETE_REQUEST";
const PRODUCTS_REVIEW_DELETE_SUCCESS = "PRODUCTS_REVIEW_DELETE_SUCCESS";
const PRODUCTS_REVIEW_DELETE_FALSE = "PRODUCTS_REVIEW_DELETE_FALSE";
const PRODUCTS_REVIEW_DELETE_RESET = "PRODUCTS_REVIEW_DELETE_RESET";

const PRODUCTS_NEW_REQUEST = "PRODUCTS_NEW_REQUEST";
const PRODUCTS_NEW_SUCCESS = "PRODUCTS_NEW_SUCCESS";
const PRODUCTS_NEW_RESET = "PRODUCTS_NEW_RESET";
const PRODUCTS_NEW_FALSE = "PRODUCTS_NEW_FALSE";

const PRODUCTS_DELETE_REQUEST = "PRODUCTS_DELETE_REQUEST";
const PRODUCTS_DELETE_SUCCESS = "PRODUCTS_DELETE_SUCCESS";
const PRODUCTS_DELETE_RESET = "PRODUCTS_DELETE_RESET";
const PRODUCTS_DELETE_FALSE = "PRODUCTS_DELETE_FALSE";

const PRODUCTS_UPDATE_REQUEST = "PRODUCTS_UPDATE_REQUEST";
const PRODUCTS_UPDATE_SUCCESS = "PRODUCTS_UPDATE_SUCCESS";
const PRODUCTS_UPDATE_RESET = "PRODUCTS_UPDATE_RESET";
const PRODUCTS_UPDATE_FALSE = "PRODUCTS_UPDATE_FALSE";

const PRODUCTS_LIST_ADMIN_REQUEST = "PRODUCTS_LIST_ADMIN_REQUEST";
const PRODUCTS_LIST_ADMIN_SUCCESS = "PRODUCTS_LIST_ADMIN_SUCCESS";
const PRODUCTS_LIST_ADMIN_FALSE = "PRODUCTS_LIST_ADMIN_FALSE";

const CLEAR_ERRORS = 'CLEAR_ERRORS'
module.exports = {

    PRODUCTS_LIST_REQUEST,
    PRODUCTS_LIST_SUCCESS,
    PRODUCTS_LIST_FALSE,

    PRODUCTS_DETAIL_REQUEST,
    PRODUCTS_DETAIL_SUCCESS,
    PRODUCTS_DETAIL_FALSE,

    PRODUCTS_REVIEW_REQUEST,
    PRODUCTS_REVIEW_SUCCESS,
    PRODUCTS_REVIEW_RESET,
    PRODUCTS_REVIEW_FALSE,

    PRODUCTS_REVIEW_GET_REQUEST,
    PRODUCTS_REVIEW_GET_SUCCESS,
    PRODUCTS_REVIEW_GET_FALSE,

    PRODUCTS_REVIEW_DELETE_REQUEST,
    PRODUCTS_REVIEW_DELETE_SUCCESS,
    PRODUCTS_REVIEW_DELETE_FALSE,
    PRODUCTS_REVIEW_DELETE_RESET,

    PRODUCTS_LIST_ADMIN_REQUEST,
    PRODUCTS_LIST_ADMIN_SUCCESS,
    PRODUCTS_LIST_ADMIN_FALSE,

    PRODUCTS_NEW_REQUEST,
    PRODUCTS_NEW_SUCCESS,
    PRODUCTS_NEW_RESET,
    PRODUCTS_NEW_FALSE,

    PRODUCTS_DELETE_REQUEST,
    PRODUCTS_DELETE_SUCCESS,
    PRODUCTS_DELETE_RESET,
    PRODUCTS_DELETE_FALSE,

    PRODUCTS_UPDATE_REQUEST,
    PRODUCTS_UPDATE_SUCCESS,
    PRODUCTS_UPDATE_RESET,
    PRODUCTS_UPDATE_FALSE,
    
    CLEAR_ERRORS

}