const PRODUCTS_LIST_REQUEST = "PRODUCTS_LIST_REQUEST";
const PRODUCTS_LIST_SUCCESS = "PRODUCTS_LIST_SUCCESS";
const PRODUCTS_LIST_FALSE = "PRODUCTS_LIST_FALSE";

const PRODUCTS_DETAIL_REQUEST = "PRODUCTS_DETAIL_REQUEST";
const PRODUCTS_DETAIL_SUCCESS = "PRODUCTS_DETAIL_SUCCESS";
const PRODUCTS_DETAIL_FALSE = "PRODUCTS_DETAIL_FALSE";

const PRODUCTS_REVIEW_REQUEST = "PRODUCTS_REVIEW_REQUEST";
const PRODUCTS_REVIEW_SUCCESS = "PRODUCTS_REVIEW_SUCCESS";
const PRODUCTS_REVIEW_RESET = "PRODUCTS_REVIEW_RESET";
const PRODUCTS_REVIEW_FALSE = "PRODUCTS_REVIEW_FALSE";


const PRODUCTS_LIST_ADMIN_REQUEST = "PRODUCTS_LIST_ADMIN_REQUEST";
const PRODUCTS_LIST_ADMIN_SUCCESS = "PRODUCTS_LIST_ADMIN_SUCCESS";
const PRODUCTS_LIST_ADMIN_FALSE = "PRODUCTS_LIST_ADMIN_FALSE";

module.exports = {
    PRODUCTS_LIST_REQUEST,
    PRODUCTS_LIST_SUCCESS,
    PRODUCTS_LIST_FALSE,
    PRODUCTS_DETAIL_REQUEST,
    PRODUCTS_DETAIL_SUCCESS,
    PRODUCTS_DETAIL_FALSE,
    PRODUCTS_REVIEW_REQUEST,
    PRODUCTS_REVIEW_SUCCESS,
    PRODUCTS_REVIEW_RESET,
    PRODUCTS_REVIEW_FALSE,
    PRODUCTS_LIST_ADMIN_REQUEST,
    PRODUCTS_LIST_ADMIN_SUCCESS,
    PRODUCTS_LIST_ADMIN_FALSE
}