const PRODUCTS_LIST_REQUEST = "PRODUCTS_LIST_REQUEST";
const PRODUCTS_LIST_SUCCESS = "PRODUCTS_LIST_SUCCESS";
const PRODUCTS_LIST_FALSE = "PRODUCTS_LIST_FALSE";

const PRODUCTS_DETAIL_REQUEST = "PRODUCTS_DETAIL_REQUEST";
const PRODUCTS_DETAIL_SUCCESS = "PRODUCTS_DETAIL_SUCCESS";
const PRODUCTS_DETAIL_FALSE = "PRODUCTS_DETAIL_FALSE";

module.exports = {
    PRODUCTS_LIST_REQUEST,
    PRODUCTS_LIST_SUCCESS,
    PRODUCTS_LIST_FALSE,
    PRODUCTS_DETAIL_REQUEST,
    PRODUCTS_DETAIL_SUCCESS,
    PRODUCTS_DETAIL_FALSE
}