const CLEAR_ERROR = 'CLEAR_ERROR';

const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
const USER_LOGIN_FALSE = 'USER_LOGIN_FALSE';

const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
const USER_REGISTER_FALSE = 'USER_REGISTER_FALSE';

const USER_LOAD_REQUEST = 'USER_LOAD_REQUEST';
const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
const USER_LOAD_FALSE = 'USER_LOAD_FALSE';

const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
const USER_LOGOUT_FALSE = 'USER_LOGOUT_FALSE';

const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
const USER_UPDATE_FALSE = 'USER_UPDATE_FALSE';
const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
const USER_UPDATE_PASSWORD_FALSE = 'USER_UPDATE_PASSWORD_FALSE';
const USER_UPDATE_PASSWORD_RESET = 'USER_UPDATE_PASSWORD_RESET';

const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
const USER_FORGOT_PASSWORD_FALSE = 'USER_FORGOT_PASSWORD_FALSE';

const USER_NEW_PASSWORD_REQUEST = 'USER_NEW_PASSWORD_REQUEST';
const USER_NEW_PASSWORD_SUCCESS = 'USER_NEW_PASSWORD_SUCCESS';
const USER_NEW_PASSWORD_FALSE = 'USER_NEW_PASSWORD_FALSE';

module.exports = {
    CLEAR_ERROR,
    USER_LOGIN_REQUEST,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FALSE,
    USER_REGISTER_REQUEST,
    USER_REGISTER_SUCCESS,
    USER_REGISTER_FALSE,
    USER_LOAD_REQUEST,
    USER_LOAD_SUCCESS,
    USER_LOAD_FALSE,
    USER_LOGOUT_SUCCESS,
    USER_LOGOUT_FALSE,
    USER_UPDATE_REQUEST,
    USER_UPDATE_SUCCESS,
    USER_UPDATE_FALSE,
    USER_UPDATE_RESET,
    USER_UPDATE_PASSWORD_REQUEST,
    USER_UPDATE_PASSWORD_SUCCESS,
    USER_UPDATE_PASSWORD_FALSE,
    USER_UPDATE_PASSWORD_RESET,
    USER_FORGOT_PASSWORD_REQUEST,
    USER_FORGOT_PASSWORD_SUCCESS,
    USER_FORGOT_PASSWORD_FALSE,
    USER_NEW_PASSWORD_REQUEST,
    USER_NEW_PASSWORD_SUCCESS,
    USER_NEW_PASSWORD_FALSE
    
}